name: mkdocs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install requirements
        working-directory: docs/
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
      - name: Deploy 🚀
        working-directory: docs/
        run: python3 -m mkdocs gh-deploy --force  
