name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build CLI
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o build/umbra-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: umbra-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/umbra-${{ matrix.goos }}-${{ matrix.goarch }}
